Make setdevenv automagically setup local.conf if it dont exist
git-svn-id: https://svn.o-hand.com/repos/poky@4 311d38ba-8fff-0310-9ca6-ca027cbcb966

diff --git a/setdevenv b/setdevenv
--- a/setdevenv
+++ b/setdevenv
@@ -4,7 +4,7 @@
 # Change this to the location of this file.
 # Also update the locations at the top of conf/local.conf
 #
-OEROOT=/usr/ohoe/
+OEROOT=`pwd`
 
 BBDIR=$OEROOT/bitbake/
 PKGDIR=$OEROOT/openembedded/
@@ -20,10 +20,15 @@ PKGDIR=`readlink -f $PKGDIR`
 BUILDDIR=`readlink -f $BUILDDIR`
 
 if ! (test -d $BBDIR && test -d $PKGDIR && test -d $BUILDDIR); then
-    echo >&2 "Error: Not all directories exist!"
+    echo >&2 "Error: Not all directories exist! Did you run this script in poky directory?"
     exit 1
 fi
-	
+
+if !(test -r $PKGDIR/conf/local.conf); then
+   echo "Setting up initial '$PKGDIR/conf/local.conf'."
+   cat $PKGDIR/conf/local.conf.sample | sed -e"s|POKYROOT|${OEROOT}|" > $PKGDIR/conf/local.conf
+fi	
+
 BBPATH=$BBDIR
 if test x"$BBDIR" != x"$PKGDIR"; then
 	BBPATH=$PKGDIR:$BBPATH
