libsolv: ptest: remove conditional checks
Simplify run-ptest and do_install_ptest by removing conditional
checks. If upstream renames or relocates test files, the build should
fail explicitly rather than silently skipping tests, ensuring the
recipe is updated appropriately.

Changes:
  - Use testcases/* glob to automatically discover all test suites
  - Remove file existence checks from run-ptest
  - Remove file existence checks from do_install_ptest

Signed-off-by: Pratik Farkase <pratik.farkase@est.tech>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

diff --git a/meta/recipes-extended/libsolv/libsolv/run-ptest b/meta/recipes-extended/libsolv/libsolv/run-ptest
--- a/meta/recipes-extended/libsolv/libsolv/run-ptest
+++ b/meta/recipes-extended/libsolv/libsolv/run-ptest
@@ -2,20 +2,11 @@
 
 cd test
 
-for t in allowuninstall alternative blacklist choicerules choose cleandeps \
-         cplxdeps distupgrade evrcmp excludefromweak favor focus forcebest \
-         lock lockstep multiversion namespace proof recommendations sat \
-         selection strictrepoprio strongrecommends targeted testcase weakdeps \
-         whatprovideswithdisabled yumobs; do
-
-    if [ -x ./runtestcases.sh ] && [ -d testcases/$t ]; then
-        ./runtestcases.sh ../tools/testsolv testcases/$t
-        if [ $? -eq 0 ]; then
-            echo "PASS: $t"
-        else
-            echo "FAIL: $t"
-        fi
+for t in testcases/*; do
+    ./runtestcases.sh ../tools/testsolv $t
+    if [ $? -eq 0 ]; then
+        echo "PASS: $t"
     else
-        echo "SKIP: $t"
+        echo "FAIL: $t"
     fi
 done
