scripts/oe-buildenv-internal: Improve message when bitbake is missing
Signed-off-by: Richard  Purdie <richard.purdie@linuxfoundation.org>

diff --git a/scripts/oe-buildenv-internal b/scripts/oe-buildenv-internal
--- a/scripts/oe-buildenv-internal
+++ b/scripts/oe-buildenv-internal
@@ -44,7 +44,7 @@ BITBAKEDIR=`readlink -f "$BITBAKEDIR"`
 BUILDDIR=`readlink -f "$BUILDDIR"`
 
 if ! (test -d "$BITBAKEDIR"); then
-    echo >&2 "Error: The bitbake directory ($BITBAKEDIR) does not exist!  Did you source the script in the correct directory?"
+    echo >&2 "Error: The bitbake directory ($BITBAKEDIR) does not exist!  Please ensure a copy of bitbake exists at this location"
     return
 fi
 
