Further cleanup of various poky references
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

diff --git a/scripts/oe-buildenv-internal b/scripts/oe-buildenv-internal
--- a/scripts/oe-buildenv-internal
+++ b/scripts/oe-buildenv-internal
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-# Poky Build Enviroment Setup Script
+# OE-Core Build Enviroment Setup Script
 #
-# Copyright (C) 2006-2007 OpenedHand Ltd.
+# Copyright (C) 2006-2011 Linux Foundation
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -44,7 +44,7 @@ BITBAKEDIR=`readlink -f "$BITBAKEDIR"`
 BUILDDIR=`readlink -f "$BUILDDIR"`
 
 if ! (test -d "$BITBAKEDIR"); then
-    echo >&2 "Error: The bitbake directory ($BITBAKEDIR) does not exist!  Did you source the script in the poky directory?"
+    echo >&2 "Error: The bitbake directory ($BITBAKEDIR) does not exist!  Did you source the script in the correct directory?"
     return
 fi
 
