oe-git-proxy: Redirect error messages to STDERR
oe-git-proxy script needs socat. If socat is not found,
an error message is issued on STDOUT. This leads to a misleading
git message:

fatal: protocol error: bad line length character: ERRO

instead of the intended message:

ERROR: socat binary not in PATH

Redirecting the error message to STDERR fixes this issue.

Signed-off-by: Juro Bystricky <juro.bystricky@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

diff --git a/scripts/oe-git-proxy b/scripts/oe-git-proxy
--- a/scripts/oe-git-proxy
+++ b/scripts/oe-git-proxy
@@ -19,7 +19,7 @@
 # Locate the netcat binary
 SOCAT=$(which socat 2>/dev/null)
 if [ $? -ne 0 ]; then
-	echo "ERROR: socat binary not in PATH"
+	echo "ERROR: socat binary not in PATH" 1>&2
 	exit 1
 fi
 METHOD=""
