scripts: Move main contents of poky-init-build-env to scripts/poky-env-internal. Add poky-autobuild script for autobuilder use.
git-svn-id: https://svn.o-hand.com/repos/poky/trunk@948 311d38ba-8fff-0310-9ca6-ca027cbcb966

diff --git a/scripts/poky-autobuild b/scripts/poky-autobuild
--- a/scripts/poky-autobuild
+++ b/scripts/poky-autobuild
@@ -19,9 +19,11 @@
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #
 
-if test x"$0" = x"./poky-init-build-env"; then
-   echo "Error: Run via '. ./poky-init-build-env'"
-   exit 1
-fi
+#if test x"$0" = x"./poky-init-build-env"; then
+#   echo "Error: Run via '. ./poky-init-build-env'"
+#   exit 1
+#fi
 
 . ./scripts/poky-env-internal
+
+bitbake $1
