runqemu: Add error handling for unexpected tap devices
In theory the code reduces the tap device number to an integer. This
patch adds error checking to ensure that does happen and that the script
exits if something unexpected happens.

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

diff --git a/scripts/runqemu-internal b/scripts/runqemu-internal
--- a/scripts/runqemu-internal
+++ b/scripts/runqemu-internal
@@ -253,6 +253,14 @@ else
 
 
         n0=$(echo $TAP | sed 's/tap//')
+
+        case $n0 in
+            ''|*[!0-9]*)
+                echo "Error Couldn't turn $TAP into an interface number?"
+                exit 1
+                ;;
+        esac
+
         n1=$(($n0 * 2 + 1))
         n2=$(($n1 + 1))
 
