scripts: Show sensible warning messages if expected binaries don't exist
[YOCTO #1438]

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

diff --git a/scripts/runqemu-gen-tapdevs b/scripts/runqemu-gen-tapdevs
--- a/scripts/runqemu-gen-tapdevs
+++ b/scripts/runqemu-gen-tapdevs
@@ -62,6 +62,10 @@ if [ -z "$IFCONFIG" ]; then
 	# Is it ever anywhere else?
 	IFCONFIG=/sbin/ifconfig
 fi
+if [ ! -x "$IFCONFIG" ]; then
+       echo "$IFCONFIG cannot be executed"
+       exit 1
+fi
 
 # Ensure we start with a clean slate
 for tap in `$IFCONFIG | grep ^tap | awk '{ print \$1 }'`; do
diff --git a/scripts/runqemu-ifup b/scripts/runqemu-ifup
--- a/scripts/runqemu-ifup
+++ b/scripts/runqemu-ifup
@@ -69,11 +69,28 @@ if [ "x$IFCONFIG" = "x" ]; then
 	# better than nothing...
 	IFCONFIG=/sbin/ifconfig
 fi
+if [ ! -x "$IFCONFIG" ]; then
+	echo "$IFCONFIG cannot be executed"
+	exit 1
+fi
 
 ROUTE=`which route`
 if [ "x$ROUTE" = "x" ]; then
 	# better than nothing...
 	ROUTE=/sbin/route
+fi
+if [ ! -x "$ROUTE" ]; then
+	echo "$ROUTE cannot be executed"
+	exit 1
+fi
+
+IPTABLES=`which iptables 2> /dev/null`
+if [ "x$IPTABLES" = "x" ]; then
+	IPTABLES=/sbin/iptables
+fi
+if [ ! -x "$IPTABLES" ]; then
+	echo "$IPTABLES cannot be executed"
+	exit 1
 fi
 
 n=$[ (`echo $TAP | sed 's/tap//'` * 2) + 1 ]
@@ -83,11 +100,6 @@ dest=$[ (`echo $TAP | sed 's/tap//'` * 2) + 2 ]
 $ROUTE add -host 192.168.7.$dest $TAP
 
 # setup NAT for tap0 interface to have internet access in QEMU
-IPTABLES=`which iptables`
-if [ "x$IPTABLES" = "x" ]; then
-	IPTABLES=/sbin/iptables
-fi
-
 $IPTABLES -A POSTROUTING -t nat -j MASQUERADE -s 192.168.7.0/24
 echo 1 > /proc/sys/net/ipv4/ip_forward
 $IPTABLES -P FORWARD ACCEPT
diff --git a/scripts/runqemu-internal b/scripts/runqemu-internal
--- a/scripts/runqemu-internal
+++ b/scripts/runqemu-internal
@@ -88,8 +88,16 @@ fi
 # sudo.
 NOSUDO_FLAG="/etc/runqemu-nosudo"
 
-QEMUIFUP=`which runqemu-ifup`
-QEMUIFDOWN=`which runqemu-ifdown`
+QEMUIFUP=`which runqemu-ifup 2> /dev/null`
+QEMUIFDOWN=`which runqemu-ifdown 2> /dev/null`
+if [ -z "$QEMUIFUP" -o ! -x "$QEMUIFUP" ]; then
+       echo "runqemu-ifup cannot be found or executed"
+       exit 1
+fi
+if [ -z "$QEMUIFDOWN" -o ! -x "$QEMUIFDOWN" ]; then
+       echo "runqemu-ifdown cannot be found or executed"
+       exit 1
+fi
 
 NFSRUNNING="false"
 
@@ -136,6 +144,10 @@ fi
 IFCONFIG=`which ifconfig 2> /dev/null`
 if [ -z "$IFCONFIG" ]; then
     IFCONFIG=/sbin/ifconfig
+fi
+if [ ! -x "$IFCONFIG" ]; then
+       echo "$IFCONFIG cannot be executed"
+       exit 1
 fi
 
 POSSIBLE=`$IFCONFIG -a | grep '^tap' | awk '{print $1}'`
@@ -418,7 +430,7 @@ fi
 
 PATH=$CROSSPATH:$OECORE_NATIVE_SYSROOT/usr/bin:$PATH
 
-QEMUBIN=`which $QEMU`
+QEMUBIN=`which $QEMU 2> /dev/null`
 if [ ! -x "$QEMUBIN" ]; then
     echo "Error: No QEMU binary '$QEMU' could be found."
     cleanup
@@ -434,7 +446,7 @@ function _quit() {
     return
 }
 
-DISTCCD=`which distccd`
+DISTCCD=`which distccd 2> /dev/null`
 PIDFILE=""
 
 trap _quit INT TERM QUIT
